### ISSUE TITLE
`typed-api` fails instanceof check for Zod object schemas

### ISSUE THREAD

**Issue by NuroDev** [lilnasy/gratelets#52] opened 2024-01-02 17:43 UTC
Just testing out the `astro-typed-api` package & so far it's looking very promising. However one quick issue that I ran into immediately is that [this check](https://github.com/lilnasy/gratelets/blob/main/packages/typed-api/runtime/server.ts#L29-L31) is running if you provide a Zod object schema (`z.object({ ... })`).

### Example

```ts
// src/pages/api/hello.ts
import { defineApiRoute } from 'astro-typed-api/server';
import { z } from 'zod';

export const GET = defineApiRoute({
	schema: z.object({
		name: z.string(),
	}),
	fetch: ({ name }) => `Hello, ${name}!`,
});
```

If you try to query this you get the following error:
```log
API Route defines a schema, but the schema is not a valid zod schema.

The schema must be an instance of ZodType.
```

### Cause

The issue being, as I mentioned above, being [this check](https://github.com/lilnasy/gratelets/blob/main/packages/typed-api/runtime/server.ts#L29-L31) which seems to only check if the provided schema if of one possible sort of Zod schema. In this case something like a string.

Maybe switching this to a nullish check for a `_def` property inside the schema object may be better? And then if you want to get more specific check the schema definition type to limit which ones are allowed / supported. Otherwise you may need a lengthy check for all possible Zod classes that are and aren't supported.

**Comment by lilnasy** [comment] 2024-01-02 17:59
That is odd. `ZodType` is the abstract class all other schema shapes inherit from. Could it be conflicting zod versions?

**Comment by NuroDev** [comment] 2024-01-02 18:18
Ah, you are correct. My mistake. I didn't have `zod` installed locally. For whatever reason the Zod nullish check didn't get flagged. I guess it imported Astro's version of Zod probably.

Either way that seemed to fix that error. However I now get a new error, naturally, complaining that top-level `await` is not supported (yet)
```log
Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
```

**Comment by lilnasy** [comment] 2024-01-02 18:24
Yep, it was brought up before. Cloudflare's settings are kinda strict, I think it's from the adapter's extra processing. Doesn't matter though, the import doesn't need to be top-level.

**Comment by lilnasy** [comment] 2024-01-02 20:21
@NuroDev I thought it was the cloudflare adapter but maybe not, I was able to build correctly with it. Is there something else in your project that could be involved?

**Comment by amanketebo** [comment] 2024-01-03 03:21
Hey y'all I'm also seeing that same error:

`Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)`

It seems to be referencing this part of the code:
<img width="695" alt="Screenshot 2024-01-02 at 7 19 28 PM" src="https://github.com/lilnasy/gratelets/assets/14272404/79e0dd51-4c36-4cac-985f-b41755a8da16">

I've tried changing the target to es2022 in the astro config file and a few other things in stackoverflow with no luck. Going to keep looking into it but just wanted to post here too

**Comment by amanketebo** [comment] 2024-01-03 03:21
Oh wait, I missed your PR haha okay glad that will fix it. Thanks @lilnasy!

**Comment by lilnasy** [comment] 2024-01-03 17:15
Released `astro-typed-api@0.1.2` with a fix. Since I couldn't reproduce the error, I'll let one of you confirm before closing.

**Comment by amanketebo** [comment] 2024-02-06 05:04
@lilnasy My bad forgot to circle back here, yup all is good now. Thanks!

**Comment by lilnasy** [comment] 2024-02-06 13:40
Thanks!

**Closed by lilnasy** 2024-02-06 13:40 UTC
Labels: P4: important, pkg: typed-api
